# Generated by Django 3.2 on 2021-04-16 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20210416_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 16, 12, 13, 15, 807182, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
