# Generated by Django 3.2 on 2021-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20210416_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
