# Generated by Django 3.2 on 2021-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_transcations_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcations',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='transcations',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='transcations',
            name='date',
            field=models.DateField(default='2021-04-16'),
            preserve_default=False,
        ),
    ]
