# Generated by Django 3.2 on 2021-04-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_auto_20210417_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=20, null=True),
        ),
    ]
