# Generated by Django 3.2 on 2021-04-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=20, null=True),
        ),
    ]
